App\Application\Entity\Segment:
    type: entity
    table: segment
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'primary key'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createTime:
            type: datetime
            nullable: true
            options:
                comment: 'create time'
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            options:
                comment: 'update time'
            column: update_time
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                comment: Label
    lifecycleCallbacks: {  }
