App\Application\Entity\CarManagement:
    type: entity
    table: car_management
    indexes:
        car_id:
            columns:
                - car_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'primary key'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createTime:
            type: datetime
            nullable: true
            options:
                comment: 'create time'
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            options:
                comment: 'update time'
            column: update_time
        dateFrom:
            type: datetime
            nullable: false
            column: date_from
        dateTo:
            type: datetime
            nullable: true
            column: date_to
    manyToOne:
        car:
            targetEntity: App\Application\Entity\Car
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                car_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: App\Application\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
