<?php

namespace App\Application\Repository;

use App\Application\Entity\Car;
use App\Application\Entity\CarManagement;
use App\Application\Entity\Segment;
use App\Application\Entity\Status;
use App\Application\Entity\User;

/**
 * CarManagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarManagementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Panel retrieval
     *
     * @return void
     */
    public function retrieveCarManagementPanel()
    {
        $queryBuilder = $this->createQueryBuilder('q');
        $queryBuilder
            ->select(
                'cm.dateFrom,'
                . ' cm.dateTo,'
                . ' c.carNumber,'
                . ' c.yearMade,'
                . ' c.model,'
                . ' s.name AS status,'
                . ' u.email,'
                . ' ss.name AS segment'
            )
            ->from(CarManagement::class, 'cm')
            ->innerJoin(Car::class, 'c')
            ->join(Status::class, 's')
            ->innerJoin(User::class, 'u')
            ->join(Segment::class, 'ss')
            ->setFirstResult(1)
            ->setMaxResults(20);

        return $queryBuilder->getQuery()->getArrayResult();
    }
}
